sudo: required

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop

before_script:
  - docker-compose -f "docker-compose.yml" up -d --build

script:
  - docker exec -it web python3 manage.py test

after_script:
  - docker-compose -f "docker-compose.yml" down --remove-orphans