version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: /bin/bash -l -c 'python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db