# Generated by Django 2.0.8 on 2018-11-19 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('intervalo', models.TimeField()),
                ('horario_Ini', models.TimeField()),
                ('qtd', models.PositiveIntegerField()),
                ('limite', models.TimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_integrador.Slot'),
        ),
    ]
