# Generated by Django 2.0.8 on 2018-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=20)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
    ]
